import { execSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { SiteConfig, ComposeContext } from './types';
import { TRAEFIK_COMPOSE_FILE, TRAEFIK_NETWORK, LOCAL_DB_PASSWORD } from './constants';

export const siteComposePath = (siteSlug: string): string =>
    path.join(os.homedir(), 'wp-sites', `${siteSlug}.yml`);

/** Creates the shared wp-local network and starts Traefik + MailHog if not already running */
export const ensureInfraRunning = (): void => {
    try {
        execSync(`docker network inspect ${TRAEFIK_NETWORK}`, { stdio: 'pipe' });
    } catch {
        execSync(`docker network create ${TRAEFIK_NETWORK}`, { stdio: 'pipe' });
    }
    execSync(`docker compose -f ${TRAEFIK_COMPOSE_FILE} up -d`, { stdio: 'inherit' });
};

/** Generates a self-contained docker-compose.yml for the site at ~/wp-sites/<slug>.yml */
export const generateSiteCompose = (
    config: SiteConfig,
    siteSlug: string,
    localWpPath: string,
    localDbName: string
): void => {
    const themeMount = config.THEME_GIT_PATH && config.THEME_WP_FOLDER
        ? `\n      - ${config.THEME_GIT_PATH}:/var/www/html/wp-content/themes/${config.THEME_WP_FOLDER}`
        : '';

    const content = `# Auto-generated by clone script — do not edit manually
services:
  wordpress:
    image: wordpress:php8.1-apache
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wp-local
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.${siteSlug}.rule=Host(\`${siteSlug}.localhost\`)
      - traefik.http.routers.${siteSlug}.entrypoints=web
      - traefik.docker.network=wp-local
    volumes:
      - ${localWpPath}:/var/www/html${themeMount}
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DB_PASSWORD}
      MYSQL_DATABASE: ${localDbName}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${LOCAL_DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped

networks:
  wp-local:
    external: true

volumes:
  mysql-data:
`;

    const composePath = siteComposePath(siteSlug);
    fs.mkdirSync(path.dirname(composePath), { recursive: true });
    fs.writeFileSync(composePath, content);
};

const composeCmd = (ctx: ComposeContext): string =>
    `docker compose -p ${ctx.projectName} -f ${ctx.composePath}`;

export const startSiteService = (ctx: ComposeContext, service: string): void => {
    execSync(`${composeCmd(ctx)} up -d ${service}`, { stdio: 'inherit' });
};

export const startSiteAll = (ctx: ComposeContext): void => {
    execSync(`${composeCmd(ctx)} up -d --force-recreate`, { stdio: 'inherit' });
};

export const siteExec = (ctx: ComposeContext, service: string, cmd: string): string =>
    `${composeCmd(ctx)} exec -T ${service} ${cmd}`;
